sudo: required
language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - sudo apt-get install gir1.2-gtk-3.0 at-spi2-core gobject-introspection libgirepository1.0-dev libglib2.0-dev intltool libgnutls-dev xvfb
  - pip install Sphinx
  - pip install translate-toolkit
  - pip install python-Levenshtein
  - pip install lxml
  - pip install pycurl
  - pip install diff_match_patch
  - pip install pygobject
  - pip install pytest
script:
  - ./maketranslations
  - make docs
  - find docs/_build/html
  - python setup.py install
  - find -name \*py -exec python -m py_compile {} +
  - xvfb-run -a --server-args="-screen 0 1024x768x24" pytest -rvxs virtaal
  - xvfb-run -a --server-args="-screen 0 1024x768x24" virtaal --help
notifications:
  email:
    on_failure: change
    on_success: change
