# https://travis-ci.org/#!/translate/virtaal
language: python
python:
  - 2.6
  - 2.7
install:
  - pip install Sphinx
  - pip install translate-toolkit
  - pip install python-Levenshtein
  - pip install lxml
  - pip install pycurl
  - sudo apt-get install python-gtk2
script:
  - make docs
  - python setup.py install
notifications:
  email:
    on_failure: change
    on_success: change
